name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Prepare for Yarn Installation
        run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - name: install yarn
        run: sudo apt update && sudo apt install yarn
      - name: Font-Awesome SVG-Core Installation
        run: yarn add @fortawesome/fontawesome-svg-core
      - name: font awesome solid svg icon installation
        run: yarn add @fortawesome/free-solid-svg-icons
      - name: font awesome react-version
        run: yarn add @fortawesome/react-fontawesome
      - name: Build React App
        run: yarn build
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./build todo-application-alizafar.surge.sh --token ${{secrets.SURGE_TOKEN}}
